=== maremedev/XML/ecole.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> 
<xs:element name="eleve">
    <xs:complexType >
      <xs:sequence>
        <xs:element name="matricule" type="xs:String"/>
        <xs:element name="nom"/>
        <xs:element name="prenom"/>
        <xs:element name="DateNaissance" type="xs:date"/>
          <xs:element name="Classe" >
               <xs:simpleType >
                 <xs:restriction base="xs:string">
                    <xs:enumeration value="6ème"/>
                    <xs:enumeration value="5ème"/>
                    <xs:enumeration value="4ème"/>
                    <xs:enumeration value="3ème"/>
                    <xs:enumeration value="2nde"/>
                    <xs:enumeration value="1ère"/>
                    <xs:enumeration value="Terminale"/>
                  </xs:restriction>
               </xs:simpleType>
          </xs:element>
              <xs:element name="Sexe" >
                <xs:simpleType >
                  <xs:restriction base="xs:string">
                      <xs:enumeration value="M"/>
                      <xs:enumeration value="F"/>
                   </xs:restriction>
                </xs:simpleType>
              </xs:element>
       </xs:sequence>
    </xs:complexType>  
</xs:element>  
<xs:element name="matieres">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="matiere" type="xs:string" maxOccurs="unbounded"/>
        <xs:element name="Codematiere">
        <xs:simpleType >
    <xs:restriction base="xs:string">
      <xs:pattern value="MAT-\d{3}"/>
    </xs:restriction>
  </xs:simpleType>

      <xs:element name="nom" >
  <xs:simpleType >
    <xs:restriction base="xs:string">
      <xs:enumeration value="Mathématiques"/>
      <xs:enumeration value="Français"/>
      <xs:enumeration value="Anglais"/>
      <xs:enumeration value="SVT"/>
      <xs:enumeration value="Physique-Chimie"/>
      <xs:enumeration value="Histoire-Géo"/>
      <xs:enumeration value="EPS"/>
    </xs:restriction>
  </xs:simpleType>
  </xs:element>
      <xs:element name="Coefficient">
  <xs:simpleType >
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="5"/>
    </xs:restriction>
  </xs:simpleType>
      <xs:element name="professeur" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
   <xs:complexType>
   <xs:sequence>
  <xs:element name="notes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="note" type="xs:decimal" maxOccurs="unbounded"/>
         <xs:element name="matricule" >
         <xs:simpleType >
    <xs:restriction base="xs:string">
      <xs:pattern value="ELEVE-\d{4}"/>
    </xs:restriction>
  </xs:simpleType>
   </xs:element>

      <xs:element name="Codematiere">
       <xs:simpleType >
    <xs:restriction base="xs:string"/>
      <xs:pattern value="MAT-\d{3}"/>
  </xs:simpleType>
  </xs:element>

    <xs:element name="trimestre"> 
    <xs:simpleType >
    <xs:restriction base="xs:integer">
      <xs:enumeration value="1"/>
      <xs:enumeration value="2"/>
      <xs:enumeration value="3"/>
    </xs:restriction>
  </xs:simpleType>
    </xs:element> 

    <xs:element name="note">
     <xs:simpleType >
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="20"/>
    </xs:restriction>
  </xs:simpleType>
    </xs:element>

    <xs:element name="type">
    <xs:simpleType >
    <xs:restriction base="xs:string">
      <xs:enumeration value="Devoir"/>
      <xs:enumeration value="Interrogation"/>
      <xs:enumeration value="Examen"/>
    </xs:restriction>
  </xs:simpleType>
     </xs:element>
     <xs:element name="date" type="xs:date"/>
      </xs:sequence>
      </xs:complexType>

      <xs:element name="Bulletins">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Bulletin" type="xs:string" maxOccurs="unbounded"/>
        <xs:element name="matricule" >
        <xs:simpleType >
    <xs:restriction base="xs:string">
      <xs:pattern value="ELEVE-\d{4}"/>
    </xs:restriction>
  </xs:simpleType>
      </xs:element>
      <xs:element name="trimestre">
      <xs:simpleType >
    <xs:restriction base="xs:integer">
      <xs:enumeration value="1"/>
      <xs:enumeration value="2"/>
      <xs:enumeration value="3"/>
    </xs:restriction>
  </xs:simpleType>
       </xs:element>
      <xs:element name="anneescolaire">
       <xs:simpleType >
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{4}-\d{4}"/>
    </xs:restriction>
  </xs:simpleType>
  </xs:element>
      <xs:element name="moyenne">
      <xs:complexType >
    <xs:sequence>
      <xs:element name="codematiere" type="xs:string"/>
      <xs:element name="nom" type="xs:string"/>
      <xs:element name="moyenne" type="xs:decimal"/>
    </xs:sequence>
  </xs:complexType>
       </xs:element>
      <xs:element name="moyennegenerale" type="xs:decimal"/>
      <xs:element name="rang" type="xs:integer"/>
      <xs:element name="appreciationgenerale" type="xs:string"/>
      <xs:element name="decision">
      <xs:simpleType >
    <xs:restriction base="xs:string">
      <xs:enumeration value="Admis"/>
      <xs:enumeration value="Ajourné"/>
      <xs:enumeration value="Redouble"/>
    </xs:restriction>
  </xs:simpleType>
  </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
 </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>

=== maremedev/XML/notes.xml
<?xml version="1.0" encoding="UTF-8"?>
<notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ecole.xsd">
    <note>
        <matricule>ELEVE-001</matricule>
        <codematiere>Mat-001</codematiere>
        <trimestre>1</trimestre>
        <note>15.5</note>
        <type>Devoir</type>
        <date>12-03-2025</date>
    </note>

        <note>
            <matricule>ELEVE-002</matricule>
            <codematiere>Mat-002</codematiere>
            <trimestre>1</trimestre>
            <note>18.5</note>
            <type>Examen</type>
            <date>13-09-2022</date>
        </note>

        <note>
            <matricule>ELEVE-003</matricule>
            <codematiere>Mat-003</codematiere>
            <trimestre>1</trimestre>
            <note>12.5</note>
            <type>Intérrogation</type>
            <date>14-12-2021</date>
        </note>

            <note>
                <matricule>ELEVE-004</matricule>
                <codematiere>Mat-004</codematiere>
                <trimestre>1</trimestre>
                <note>14.5</note>
                <type>Devor</type>
                <date>17-11-2020</date>
            </note>

                <note>
                    <matricule>ELEVE-005</matricule>
                    <codematiere>Mat-005</codematiere>
                    <trimestre>1</trimestre>
                    <note>20</note>
                    <type>Examen</type>
                    <date>10-10-2015</date>
                </note>

                    <note>
                        <matricule>ELEVE-006</matricule>
                        <codematiere>Mat-006</codematiere>
                        <trimestre>1</trimestre>
                        <note>14.00</note>
                        <type>Examen</type>
                        <date>04-02-2018</date>
                    </note>

                        <note>
                            <matricule>ELEVE-006</matricule>
                            <codematiere>Mat-006</codematiere>
                            <trimestre>1</trimestre>
                            <note>19</note>
                            <type>Devoir</type>
                            <date>07-04-2023</date>
                        </note>

                            <note>
                                <matricule>ELEVE-007</matricule>
                                <codematiere>Mat-007</codematiere>
                                <trimestre>1</trimestre>
                                <note>19.5</note>
                                <type>Intérrogation</type>
                                <date>12-07-2022</date>
                            </note>

                                <note>
                                    <matricule>ELEVE-008</matricule>
                                    <codematiere>Mat-008</codematiere>
                                    <trimestre>1</trimestre>
                                    <note>10.00</note>
                                    <type>Intérrogation</type>
                                    <date>11-08-2022</date>
                                </note>

                                    <note>
                                        <matricule>ELEVE-009</matricule>
                                        <codematiere>Mat-009</codematiere>
                                        <trimestre>1</trimestre>
                                        <note>13.5</note>
                                        <type>Examen</type>
                                        <date>07-09-2026</date>
                                    </note>

                                        <note>
                                            <matricule>ELEVE-010</matricule>
                                            <codematiere>Mat-010</codematiere>
                                            <trimestre>1</trimestre>
                                            <note>17.00</note>
                                            <type>Devoir</type>
                                            <date>09-09-2012</date>
                                        </note>

                                            <note>
                                                <matricule>ELEVE-011</matricule>
                                                <codematiere>Mat-011</codematiere>
                                                <trimestre>1</trimestre>
                                                <note>15.00</note>
                                                <type>Intérrogation</type>
                                                <date>03-12-2014</date>
                                            </note>

                                                <note>
                                                    <matricule>ELEVE-012</matricule>
                                                    <codematiere>Mat-012</codematiere>
                                                    <trimestre>1</trimestre>
                                                    <note>14.00</note>
                                                    <type>Devoir</type>
                                                    <date>06-12-2009</date>
                                                </note>

                                                    <note>
                                                        <matricule>ELEVE-013</matricule>
                                                        <codematiere>Mat-013</codematiere>
                                                        <trimestre>1</trimestre>
                                                        <note>13.5</note>
                                                        <type>Intérrogation</type>
                                                        <date>13-12-2005</date>
                                                    </note>

                                                        <note>
                                                            <matricule>ELEVE-014</matricule>
                                                            <codematiere>Mat-014</codematiere>
                                                            <trimestre>1</trimestre>
                                                            <note>12.5</note>
                                                            <type>Devoir</type>
                                                            <date>15-11-2017</date>
                                                        </note>
                                                        
                                                            <note>
                                                              <matricule>ELEVE-015</matricule>
                                                              <codematiere>Mat-015</codematiere>
                                                              <trimestre>1</trimestre>
                                                              <note>10.5</note>
                                                              <type>Examen</type>
                                                              <date>22-10-2020</date>
                                                            </note>
 </notes>

=== maremedev/XML/matieres.xml
<?xml version="1.0" encoding="UTF-8"?>
<matieres xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ecole.xsd">
    <matiere>
        <codematiere>MAT-001</codematiere>
        <nom>Mathématiques</nom>
        <coefficient>3</coefficient>
        <professeur>Mr Diop</professeur>
    </matiere>
        <matiere>
            <codematiere>MAT-002</codematiere>
            <nom>Français</nom>
            <coefficient>5</coefficient>
            <professeur>Mr Ndiaye</professeur>
        </matiere>
            <matiere>
                <codematiere>MAT-003</codematiere>
                <nom>Anglais</nom>
                <coefficient>2</coefficient>
                <professeur>Mme Sall</professeur>
            </matiere>
                <matiere>
                    <codematiere>MAT-004</codematiere>
                    <nom>SVT</nom>
                    <coefficient>2</coefficient>
                    <professeur>Mme Fall</professeur>
                </matiere>
                    <matiere>
                        <codematiere>MAT-005</codematiere>
                        <nom>, Physique-Chimie</nom>
                        <coefficient>4</coefficient>
                        <professeur>Mr Diouf</professeur>
                    </matiere>
                            <matiere>
                                <codematiere>MAT-006</codematiere>
                                <nom> Histoire-Géo</nom>
                                <coefficient>5</coefficient>
                                <professeur>Mme Kane</professeur>
                            </matiere>
                                <matiere>
                                    <codematiere>MAT-007</codematiere>
                                    <nom>EPS</nom>
                                    <coefficient>1</coefficient>
                                    <professeur>Mr Faye </professeur>
                                </matiere>
                           
</matieres>
